security:
    encoders:
        App\Entity\User:
            algorithm: auto

    enable_authenticator_manager: true

    providers:
        users_in_memory:
            memory:
                users:
                    user1:
                        password: 'password1'
                        roles: ['ROLE_USER']
                    user2:
                        password: 'password2'
                        roles: ['ROLE_ADMIN']

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: users_in_memory
            # Add other configurations as needed

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/profile, roles: ROLE_USER }

    # Other security configurations go here...
