user_route:
    path: /user
    controller: App\Controller\UserController::index

app_signin:
    path: /signin
    controller: App\Controller\UserController::sign

app_signup:
    path: /signup
    controller: App\Controller\UserController::signup
